/*
 * DevCycle Client SDK API
 * Documents the DevCycle Client SDK API which powers bucketing and descisions for DevCycle's client SDKs.
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.devcycle.android.client.sdk.model

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue
import io.swagger.v3.oas.annotations.media.Schema

/**
 * Feature
 */
class Feature {
    /**
     * unique database id
     * @return _id
     */
    @get:Schema(required = true, description = "unique database id")
    @JsonProperty("_id")
    var id: String? = null

    /**
     * Unique key by Project, can be used in the SDK / API to reference by &#x27;key&#x27; rather than _id.
     * @return key
     */
    @get:Schema(
        required = true,
        description = "Unique key by Project, can be used in the SDK / API to reference by 'key' rather than _id."
    )
    var key: String? = null

    /**
     * Feature type
     */
    enum class TypeEnum(@get:JsonValue val value: String) {
        RELEASE("release"), EXPERIMENT("experiment"), PERMISSION("permission"), OPS("ops");

        override fun toString(): String {
            return value
        }

        companion object {
            fun fromValue(text: String): TypeEnum? {
                for (b in values()) {
                    if (b.value == text) {
                        return b
                    }
                }
                return null
            }
        }
    }

    /**
     * Feature type
     * @return type
     */
    @get:Schema(required = true, description = "Feature type")
    var type: TypeEnum? = null

    /**
     * Bucketed feature variation
     * @return _variation
     */
    @get:Schema(required = true, description = "Bucketed feature variation")
    @JsonProperty("_variation")
    var variation: String? = null

    /**
     * Evaluation reasoning
     * @return evalReason
     */
    @get:Schema(description = "Evaluation reasoning")
    var evalReason: String? = null
    fun id(id: String?): Feature {
        this.id = id
        return this
    }

    fun key(key: String?): Feature {
        this.key = key
        return this
    }

    fun type(type: TypeEnum?): Feature {
        this.type = type
        return this
    }

    fun variation(variation: String?): Feature {
        this.variation = variation
        return this
    }

    fun evalReason(evalReason: String?): Feature {
        this.evalReason = evalReason
        return this
    }
}