/*
 * DevCycle Client SDK API
 * Documents the DevCycle Client SDK API which powers bucketing and descisions for DevCycle's client SDKs.
 *
 * OpenAPI spec version: 1-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.devcycle.sdk.android.model

import io.swagger.v3.oas.annotations.media.Schema
import java.math.BigDecimal

/**
 * ClientSDKAPIResponse
 */
class BucketedUserConfig {
    /**
     * Get project
     * @return project
     */
    @get:Schema(required = true, description = "")
    val project: Project? = null

    /**
     * Get environment
     * @return environment
     */
    @get:Schema(required = true, description = "")
    val environment: Environment? = null

    /**
     * Mapping of &#x60;Feature.key&#x60; to &#x60;Feature&#x60; schema values.
     * @return features
     */
    @get:Schema(description = "Mapping of `Feature.key` to `Feature` schema values.")
    val features: Map<String, Feature>? = null

    /**
     * Map of &#x60;Feature._id&#x60; to &#x60;Feature._variation&#x60; used for event logging.
     * @return featureVariationMap
     */
    @get:Schema(description = "Map of `Feature._id` to `Feature._variation` used for event logging.")
    val featureVariationMap: Map<String, String>? = null

    /**
     * Map of &#x60;Variable.key&#x60; to &#x60;Variable&#x60; values.
     * @return variables
     */
    @get:Schema(description = "Map of `Variable.key` to `Variable` values.")
    var variables: Map<String, Variable<Any>>? = null

    /**
     * Hashes &#x60;murmurhash.v3(variable.key + environment.apiKey)&#x60; of all known variable keys not contained in the &#x60;variables&#x60; object.
     * @return knownVariableKeys
     */
    @get:Schema(description = "Hashes `murmurhash.v3(variable.key + environment.apiKey)` of all known variable keys not contained in the `variables` object.")
    val knownVariableKeys: List<BigDecimal>? = null
}