on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@1.0.4
      - name: Build with Gradle
        uses: gradle/gradle-build-action@2.1.0
        with:
          arguments: build