name: Release

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: "Prerelease"
        required: true
        type: boolean
      draft:
        description: "Draft"
        required: true
        type: boolean
      version-increment-type:
        description: "Which part of the version to increment:"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
        default: "patch"

permissions:
  contents: write

jobs:
  release:
    name: Version Bump and Release
    runs-on: ubuntu-latest
    outputs:
      next-release-tag: ${{ steps.prepare-release.outputs.next-release-tag }}
    steps:
      # Check out the repo with credentials that can bypass branch protection, and fetch git history instead of just latest commit
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          fetch-depth: 0

      # - uses: DevCycleHQ/release-action/prepare-release@v2.3.0
      #   id: prepare-release
      #   with:
      #     github-token: ${{ secrets.AUTOMATION_USER_TOKEN }}
      #     prerelease: ${{ github.event.inputs.prerelease }}
      #     draft: ${{ github.event.inputs.draft }}
      #     version-increment-type: ${{ github.event.inputs.version-increment-type }}

      - name: Update Version in code
        run: |
          sed -i "s/^version = \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/version = \"2.3.3\"/g" android-client-sdk/build.gradle
          sed -i "s/^implementation(\"com.devcycle:android-client-sdk:[0-9]\+\.[0-9]\+\.[0-9]\+\")/implementation(\"com.devcycle:android-client-sdk:2.3.3\")/g" README.md

      - name: Commit version change
        run: |
          git config --global user.email "github-tracker-bot@taplytics.com"
          git config --global user.name "DevCycle Automation"
          git add ./android-client-sdk/build.gradle
          git add ./README.md
          git commit -m "Release 2.3.3"

      - name: Push version change
        run: |
          git push origin HEAD:${{ github.ref_name }}
        if: inputs.draft != true

      - name: Set up Java 18
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18
          cache: "gradle"

      - name: Build and Publish To Sonatype Staging
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          ./gradlew publishAllPublicationsToMavenCentral --no-configuration-cache

      - uses: DevCycleHQ/release-action/create-release@v2.3.0
        id: create-release
        with:
          github-token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          tag: 2.3.3
          target: ${{ github.ref_name }}
          prerelease: ${{ github.event.inputs.prerelease }}
          draft: ${{ github.event.inputs.draft }}
          changelog: "Release 2.3.3"

      - name: Display link to release
        run: |
          echo "::notice title=Release ID::${{ steps.create-release.outputs.release-id }}"
          echo "::notice title=Release URL::${{ steps.create-release.outputs.release-url }}"

  # TODO: update this workflow with the appropriate permissions
  # update-flutter-sdk:
  #   uses: DevCycleHQ/flutter-client-sdk/.github/workflows/update-android-sdk-version.yaml@main
  #   needs: release
  #   if: inputs.draft != 'true'
  #   with:
  #     target-version: ${{ needs.release.outputs.next-release-tag }}
  #   secrets: inherit
  #   permissions:
  #     contents: write
  #     pull-requests: write
