name: Unit Test
permissions:
  contents: read
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ac638b061dabc8c73936c7dc2af2d0b0c4ae5250 # v4.4.1
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
