name: Unit Test
permissions:
  contents: read
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 18
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@384cd31388782f4106dc4a1b37eea2ff02e0aad7 # v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
